apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
spec:
  persistence:
    storageClassName: hostpath
    storage: 10Mi
  resources:
    requests:
      cpu: 1000m
      memory: 100Mi
    limits:
      cpu: 2000m
      memory: 2000Mi
