### Compute perm
POST http://localhost/api/perm/compute
Content-Type: application/json

{
    "term": 9,
    "computeDelay": 10
}

### Fetch perms
GET http://localhost/api/perm/compute?limit=5&offset=0