# You had 'SimpleBinary' here, which is also a typo. It should be 'SingleBinary'.
deploymentMode: SingleBinary

# The key here MUST be 'singleBinary' (lowercase 's')
singleBinary:
  replicas: 1

write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0

test:
  enabled: false

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: fileSystem
    filesystem:
      chunks_directory: /var/loki/chunks
  useTestSchema: true

# This block deploys the Memcached pod for CHUNKS
# and also tells Loki to USE it.
chunksCache:
  enabled: true
  # We set resources directly to override the "allocatedMemory: 8192" default
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

# This block deploys the Memcached pod for RESULTS
# and also tells Loki to USE it.
resultsCache:
  enabled: true
  # We set resources directly to override the "allocatedMemory: 1024" default
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m
