name: LogTest

on:
    pull_request:
        branches:
            - main
        paths:
            - log/**/*
            - .github/workflows/log*
    push:
        branches:
            - main
        paths:
            - log/**/*
            - .github/workflows/log*
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: log

        strategy:
            matrix:
                node_version: [20.x]

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node_version }}

            - name: install dependencies
              run: npm i

            - name: run test
              run: npm run test:ci
